# -*- coding: utf-8 -*-
"""Spacy final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13d9zGo33rmXjTNRVZzKct-3wasRQdQfk
"""

# Load a spacy model and chekc if it has ner
import spacy
nlp=spacy.load('en_core_web_sm')

nlp.pipe_names
#> ['tagger', 'parser', 'ner'

article_text='''Ocean Robin Shipping Holding

Email: hdy@oceanrobin.cn

***************************************

 

 

 

MV XIN HAI TONG 22       2011 56779 DWT  4X30MT CRANE WL   ANTWERP  2/11 SEPT

bod : abt 700-750mt for vlsfo and abt 220-240 mt for lsmgo

 

M.V.  XIN HAI TONG 22 
IMO No.           9453250
Type of vessel:Bulk Carrier
Built Date: March 2011
Flag :  HONG KONG
Class :  NK
DWT/Draft:  56779.5 MT ON 12.8 M SSW
GRT/NRT: 32,919 /19,132
TPC : 58.8MT at full summer draft
LOA/Beam : 189.99M / 32.26M
LBP : 185m
Depth moulded : 18 m
Suez  NT: 30466.34  ; GRT: 33913.19
Tropical salt : 58352.8 MT / 13.35 m
Winter salt : 55208.8 MT / 12.533m
Ho/Ha : 5/5
Hatch size :
no.1 : 18.86m x 18.26m
no.2-5 : 21.32m x 18.26m
Hold capacity :
no.1/2/3/4/5 :  13009.86/ 15333.25/ 14553.08/ 15333.27/ 13404.64cbm
Grain: 71634.10 CBM
Hatch cover strength: 2.3T/M2
Tank top strength (MT/m2) : Holds 1-3-5: 25T/M2, Holds 2-4: 20T/M2
Gears : Cranes: 4X30 mt  TTS ELECTROHYDRAULIC
Grabs: 4X12cbm

SPEED AND CONSUMPTION FIGURES:
SPEED LADEN CONSUMPTION (MT/DAY) / BALLAST CONSUMPTION (MT/DAY)
ABT 13KTS ABT 29.5MT IFO+ABT 0.1MT LSMGO / ABT 13KTS ABT 27.5MT IFO+ABT 0.1MT LSMGO 
ALTERNATIVE SPEED/CONSUMPTION:
LADEN ABT 12KTS ABT 24.0MT IFO+ABT 0.1MT LSMGO / BALLAST ABT 12KTS ABT 21.50MT IFO+ABT 0.1MT LSMGO
ABOVE CONSUMPTIONS INCLUDE MAIN ENGINE AND AUX.ENGINE CONSUMPTIONS.
CONSUMPTION IN PORT (IN ECA PORT CONSUMPTIONS WILL BE IN LSMGO)

 DAILY CONSUMPTION BASIS GEARS WORKING: ABT4.50MT LSFO + 0.1 MT LSMGO 
 IDLE (ANCHORED/STANDBY): 2.50MT LSFO + ABT 0.1MT LSMGO   
ADDITIONAL 1.50MT IFO 380CST DAILY FOR BOILER CONSUMPTION WITH TEMPERATURE LESS THAN 10 DEGREE CENTIGRADE.

 

(A) AVERAGE SPEED AND AVERAGE CONSUMPTION TO BE CALCULATED FROM SEA BUOY TO SEA BUOY EXCLUDING PERIODS OF SLOW STEAMING ON CHARTERERS

ORDER OR FOR REASONS OF SAFETY OR STANDING BY OR ASSISTING ANOTHER VESSEL IN DISTRESS.

(B) SPEED AND CONSUMPTION BASIS GOOD WEATHER CONDITIONS OF UP TO BEAUFORT FORCE 4 AND DOUGLAS SEA STATE 3 (SIGNIFICANT HEIGHT MAX 1.25M)WITH NO NEGATIVE SWELL NO ADVERSE CURRENTS.

(C) THE EFFECTS OF CURRENTS DURING PERIODS OF GOOD WEATHER ARE TO BE EXPRESSLY EXCLUDED FROM THE PERFORMANCE ASSESSMENT.

(D)VESL MAY BURN SMALL QTYS OF LSMGO WHEN MANEUVERING IN SHALLOW&NARROW WATERS ENTERING/LEAVING PORTS/IN HEAVY WEATHER/CANAL/RIVER/BALLAST/DEBALLAST ETC.

(E) 0.5 KNOT ALLOWANCE FOR OWNER TO BE APPLIED FOR SPEED ASSESSMENT, 5% ALLOWANCE FOR OWNER TO BE APPLIED TO BUNKER CONSUMPTION.

(F) BUNKER SAVING TO OFFSET ANY TIME LOST AND VICE VERSA.

(G) BUNKER SUPPLIED BEING OF ISO8217:2017 (E)  SPECIFICATI
-------------------------------------------------------------------------------------

TELiX M
 


 

Please propose for:

 

 - MV LORENTZOS 53688/2005 4x40Cr+EH Grabs/Co2/A60 – Mina Saqr 1st Sept

*** ferts clean / last cargo grains / b4 at drydock ***

 

++

 

- MV AKTI          57936/2014 4x30Cr+Grabs (TESS 58)       - Ganyu, China 5/8 Sept

 



 



Best Regards
        
Yorgos Floros
Dir Line +30 210 0086785
Mob +30 6948264397
Skype Floreone1
-------------------------------------------------------------
FM: VEGA STAR MARITIME SA
TEL:+30210-4287243/9855611, FAX:+30210-4287216
01/09/2022, 09:46:47, e-mail:chartering@vegastar.gr, Ref:328751-SK




GD DAY

PLS PROPOSE RATED TONNAGE FOR :

A/C Fullinks Marine Company Limited
SMX-UMX, within 20 years Β 
Del: 1 SP South Kalimantan, Indonesia
Laycan:8-14 Sep, 2022
Redel: 1 SP China (int cjk upto north china)Β 
Int coal in bulk
ADD:3.75% comm pus

-------------------------------------------------------------

cean Robin Shipping Holding

Email: hdy@oceanrobin.cn

***************************************

 

 

 

MV MEDI ADRIATICO    10 LIB DWT 61K   TAMPA 19 SEPT

bod:abt 545mt/mt

last 6 cgo:general cargo, concentrates, general cargo, iron ore, concentrates, clinker

 

 

MV MEDI ADRIATICO

VESSEL (IMO)  : MEDI ADRIATICO  (9774434 )

BUILT         : JUN 10, 2016.

FLAG : LIBERIA.

TYPE : BULKCARRIER.

SDWT : 60,550 METRIC TONNES.

SDRAFT : 12.85 METRES.

LOA : 199.98 METRES.

BEAM : 32.26 METRES.

HOLDS : 5

CAPACITY : GRAIN / BALE.

HOLD#1 : 12594 CU. METRES / 12241 CU. METRES.

HOLD#2 : 16612 CU. METRES / 16264 CU. METRES.

HOLD#3 : 15811 CU. METRES / 15462 CU. METRES.

HOLD#4 : 16597 CU. METRES / 16266 CU. METRES.

HOLD#5 : 14904 CU. METRES / 14684 CU. METRES.

TOTAL : 76518 CU. METRES / 74917 CU. METRES.

HATCHES : JACK KNIFE FOLDING TYPE.

HATCH DIM : HATCH #1: 17670MM X 18600MM.

HATCH #2, #4: 23250MM X 18600MM.

HATCH #3: 21390MM X 18600MM.

HATCH #5: 22320MM X 18600MM.

TANKTOP STR : HOLD #1: 25 MT/SQM.

HOLD #2, #4: 20 MT/SQM.

HOLD #3: 24.3 MT/SQM.

HOLD #5: 24.1 MT/SQM.

CLASS : AMERICAN BUREAU OF SHIPPING.

TPC : 60.10 METRIC TONNES.

GRT : 34049.

NRT : 19883.

CRANES : 4 X 30 METRIC TONNES + GRABS.

HULL : DOUBLE BOTTOM.

P AND I : STANDARD CLUB.

SPEED AND CONSUMPTION:

BALLAST : ABT 13.00 KN ON ABT 20.5 MTS LSIFO.

LADEN : ABT 13.00 KN ON ABT 24.5 MTS LSIFO.

ECO SPEED AND CONSUMPTION WOG

BALLAST ABT 12 KN ON LSIFO ABT17.5MT.

LADEN ABT 11 KN ON LSIFO ABT17.5MT.

IN PORT CONSUMPTION:

IFO IDLE ABT 3.0MT.

IFO WORKING ABT 6.0MT.

ADA

 

B.RGDS./JOHNSON

office line:0086 10 85934611

mobile: 0086 13811677085

Skype: Johnson_ors
-----------------------------------------------------------------------

Ocean Robin Shipping Holding

Email: hdy@oceanrobin.cn

***************************************

 

 

MV GLORY SEA     11 HK 56,623 12.8 5HH 4X30+4X12   PECEM  5/10  SEPT

*bod 750/70 mt

*prefer fh




MV.GLORY SEA

-2011 BUILT / HONGKONG  FLAG

-CLASS: CCS  CLASS

-GROSS TONNAGE: 32,962

-NET TONNAGE: 19,142

-L.O. A.: 189.99 M/BEAM: 32.26M

-DWT 56,623MT ON 12.8M SSW

-5 HATCHES/5 HOLDS, GEARED BULK CARRIER CRANE 4X30MT WITH VARIABLE MAX. 4X24MT  RADIO REMOTE CONTROL CLAMSHELL GRAB WITH MAX 12CBM.

-TYPE OF HATCH COVERS: “ TTS HUAHAI ” HOld .1 : one folding pair, opening direction FORWARD /Hold .2-5: two folding pair, opening direction

forward and aftward  WITH FLAT TOP AND OUT-PLACED HYDRAULIC CYLINDER

 

HATCH SIZE (L X W IN M):

HOLD 1: ABT. 18.86 X 18.26

HOLD 2: ABT. 21.32 X 18.26

HOLD 3: ABT. 21.32 X 18.26

HOLD 4: ABT. 21.32 X 18.26

HOLD 5: ABT. 21.32 X 18.26

 

HOLD SIZE (L X W X H) IN M HOLD 1: 27.88 X 32.26 X 16.76

HOLD 2: 31.16 X 32.26 X 16.72

HOLD 3: 29.52 X 32.26 X 16.72

HOLD 4: 31.16 X 32.26 X 16.72

HOLD 5: 29.52 X 32.26 X 16.72

 

GRAIN CAPACITY :

NO.1 HOLD ABT 13,009 M3 

NO.2 HOLD ABT 15,333 M3 

NO.3 HOLD ABT 14,553 M3 

NO.4 HOLD ABT 15,333 M3 

NO.5 HOLD ABT 13,404 M3

 

 

SPEED / DAILY CONSUMPTION

 

LADEN:

ABT. 13.0 KNOTS ON ABT. 27.5 MT/DAY OF IFO + ABT 2.5 MT/DAY FOR 1 A/E + ABT 0.1 MT MGO

BALLAST: 

ABT. 13.5 KNOTS ON ABT. 27.5 MT/DAY +ABT 2.5 MT/DAY FOR 1 A/E + ABT 0.1 MT MGO

 

 

ECO SPEED WOG 

（ L ） ABOUT 12 KNOTS ON ABT 23.5 MT/DAY IFO + ABT. 2.5 MT/DAY FOR 1 A/E + ABT 0.1 MT MGO

（ B ） ABT 12.5 KNOTS AT ON 23.5 MT/DAY IFO + ABT. 2.5 MT/DAY FOR 1 A/E + ABT 0.1 MT MGO




IN PORT

IDLE: BOILER CONSUMPTION ABT 1.0 MT RMG 380 / DAY + ABT 0.2MT MGO /DAY + ABT 2.5 MT RMG 380 FOR ONE AE.

 

WORKING: BOILER CONSUMPTION ABT 1.0 RMG 380 / DAY + ABT 0.2MT MGO /DAY + ABT 3.5 MT RMG 380 FOR AE（8HRS WORKING TIME） OR ABT 4.5MT RMG 380 FOR AE( 16 HRS WORKING TIME) OR ABT 5.5MT RMG 380 FORAE (24 HRS WORKING TIME)

 

BUNKER QUALITY: RMG 380 / DMA AS PER ISO 8217:2017 AND ALWAYS TO COMPLY WITH MARPOL 73/78 REQUIREMENTS, REG 14, 18 OF ANNEX VI AND ANY SUBSEQUENT AMENDMENTS THERETO. WHEN TRADING SPECIAL EMISSIONS CONTROL AREA (SUCH AS BALTIC SEA, ENGLISH CHANNEL, NORTH SEA) WHERE SULPHUR CONTENT TO BE MAX 0.1 PCT AS PER MARPOL ANNEX VI. IN CASE OF CALLING EU PORTS WHERE THE REQUIREMENTS OF EU DIRECTIVE 2005/33/EC APPLY THEN LSMGO GRADE DMA TO BE ACCORDING TO ISO8217:2017 AND TO HAVE MINIMUM VISCOSITY CST AT 40C.

 

VESSEL SPEED/CONSUMPTION IS GIVEN AND DETERMINED BASIS  “ GOOD WEATHER ”  CONDITIONS WHICH  ARE DESCRIBED AS WINDS NOT EXCEEDING BEGINNING BEAUFORT 4 I.E. 11KTS, AND COMBINED WIND DRIVEN SEA AND SWELL NOT EXCEEDING COMBINED SEA HEIGHT (SIGNIFICANT WAVE HEIGHT) OF 1.25 MTRS. GOOD WEATHER PERIODS MUST BE FULL STEAMING DAY. NO ADVERSE CURRENTS. NO NEGATIVE INFLUENCE OF SWELL.

 

'ABOUT' TO MEAN AN ALLOWANCE OF -0.5 KNOTS ON SPEED AND +5% ON CONSUMPTION. ANY LOSS OF TIME AND/OR OVERCONSUMPTION TO BE OFFSET BY ANY TIME AND OR BUNKERS SAVED RESPECTIVELY

 

VESSEL TO BE MONITORED STRICTLY IN ACCORDANCE WITH THE CP.

CHARTERERS HAVE OPTION TO INSTRUCT THE VSL TO SAIL UNDER ECONOMIC SPEED AND CONSUMPTION AT SEA OR SLOW STEAM THE VSL AT ANY TIME DURING THE COURSE OF THIS CHARTER PARTY ON THE BASIS OF SPEEDS AND CONSUMPTIONS WHICH TO BE ADVISED, BUT ALWAYS WITHIN A RANGE SAFE, OPERABLE AND HARMLESS TO THE ENGINE. NEVERTHELESS OWNERS/MASTER/CHIEF ENGINEER ALWAYS TO DO UTMOST TO ASSIST CHARTERERS IN THEIR REQUIREMENTS.

 

CHARTERERS TO ALLOW FOR VESSEL TO COMPLY WITH ECA AREA RESTRICTIONS AND FOLLOW PROCEDURES INTRODUCED TO PREVENT LOP (LOSS OF PROPULSION) PROBLEMS WHEN CHANGING OVER BETWEEN IFO/MGO, WHILST ENTERING OR DEPARTING FROM ANY ECA (EMISSION CONTROL ZONE) AREA AS RECOMMENDED BY ENGINE MAKER AND ALLOW FOR A 6 HOURS WINDOW FOR VESSEL TO PERFORM SAFE CHANGEOVER IN ORDER TO COMPLY WITH ECA REGULATIONS. VESSEL CONSUMES MGO IN THE ENGINES WHILE CHANGING BALLAST WATER, BALLASTING/DE-BALLASTING, CLEANING VESSEL'S HOLDS, SURVEYS, MAINTENANCE, ENTERING AND LEAVING PORTS/CANALS AND WHEN MANOEUVRING IN HAZARDOUS OR CONFINED WATERS.

ALL DETAILS ABOUT

 

B.RGDS./JOHNSON

office line:0086 10 85934611

mobile: 0086 13811677085

Skype: Johnson_ors
---------------------------------------------------------------------------------------

From: M&F CHARTERING <chartering@mnfchart.gr>
Date: Thu, Sep 1, 2022 at 12:23 PM
Subject: Klima/ 56'/ Chitta (REF:2209KAU)
To: M&F CHARTERING <chartering@mnfchart.gr>


TELiX MSG: 09KAU 01/09/22 09:53


M&F CHARTERING S.A.       Tel: (+30)210-4527500 - www.mnfchart.gr
Chartering: chartering@mnfchart.gr - Post fixing: ops@mnfchart.gr
=============================================================

-/ Nikos

Dir/Cls

OPEN CHITTAGONG 7-11 SEPT  AGW WP

LAST CARGO SCRAP
TRY ANY
BUNKERS: ABT 940-980 VLSFO AND ABT 215 - 225 LSMGO

FULL DESCRIPTION ATTACHED

MV KLIMA
56,752 MT DWT ON ABT 12,80M SSW , TPC 58,81
BLT 01/2013
GRT/NRT 33,044/19,231 ABT
FLAG: MALTA
LOA/BEAM 189,99/32,26 M
CLASS BV
ABT 71.634 CBM GRAIN CAPACITY/ 68,200 CBM BALE CAPACITY
5 HO/HA
CRANES 4 X 30 TNS (IN HOOK MODE BUT  LESS IN GRAB MODE)
+ GRABS 4 X 12 CBM EACH
ADA


Best Regards / Nikos Glyptis
Dir: +30 2104527514
Mob: +30 6946005818
Skype: nglyptis

-------------------------------------------------------------------------------------

Doc-No. 1608091   01/SEP/2022 (THU)  09:51  (+0300)  AG

 

TNS Shipbrokers and Agents Ltd (Since 1991)

phone:+359 56 841005/6, fax:+359 56 840299

home page:www.tns-shipping.com

email: chart@tns-shipping.com

 

/ Antoniya

 

Good day,

 

 

Please propose for foll close dir:

 

 

- MV PROTECTOR ST. JOHN

- OPEN, SAFI, MOROCCO 8  – 12TH SEPTEMBER ‘22

- LAST 3 CARGOES: COAL / SULPHUR / RIVER SAND

- BOD: LSFO ABT 1075 – 1125 MT / LSMGO ABT 55 – 60 MT

 

- LOOKING TO BRING HE TO PG/WCI BUT CAN TRY ANY W/I MED ECSA CARGOS

- DIRTY CARGO CAN TRY

- CAN TRY SP 3/5 OR 4/6 MTHS

 

++

MV PROTECTOR ST. JOHN

TYPE OF VESSEL GEARED,

SDBC BUILT YEAR, PLACE   2012 COSCO ZHOUSHAN

FLAG LIBERIA

PORT OF REGISTRY NO MONROVIA

IMO NO  9474656

CLASS    KR

DWT

SUMMER DWT ABT 56,562 MT ON ABT 12.8 MTRS

LOA    189.99 M BEAM/ DEPTH M.  32.26 M/ 18 M

HO/ HA    5/5

HATCH SIZE   H1 18.86X18.26M, H2-H5 21.32X18.26M

GRAIN (CBM) 71,634.08

GRT/ NRT    33,035/19,221

GEARS 4 X 30 MT

GRABS     4X 12 CBM

TPC 58.8 MT

SPEED & CONSUMPTION

LADEN ABT 12.30 KNOTS ON ABT 27.50 MT/DAY VLSFO INCLUDING AUX.

BALLAST ABT 12.30 KNOTS ON ABT 25.00 MT/DAY VLSFO INCLUDING AUX.

LADEN ABT 13.00 KNOTS ON ABT 31.00 MT/DAY VLSFO INCLUDING AUX.

BALLAST ABT 13.40 KNOTS ON ABT 28.00 MT/DAY VLSFO INCLUDING AUX.

AT PORT: IDLE: ABT 3 MT/DAY VLSFO/ WORKING: ABT 5.5 MT/DAY VLSFO

VSL CONSUMES ABT 0.1 MT LSMGO/24 HRS AT SEA AND PORT.

ADDITIONALLY:

VSL CONSUMES ABT 0.1 MT LSMGO/24 HRS AT SEA AND PORT.

VSL CONSUMES ABT 2 MT VLSFO PER DAY FOR BALLASTING/DEBALLASTING/BALLAST EXCHANGE

VSL CONSUMES ABT 2 MT VLSFO PER DAY FOR C/H’S WASHING/CLEANING

COLD CLIMATE VSL CONSUMES ABT 1MT/DAY VLSFO FOR BOILER.

VESSEL’S SPEED IS GIVEN UNDER GOOD-WEATHER CONDITION, 24 CONSECUTIVE HRS NOON TO NOON, WHICH IN TURN IS DEFINED AS WEATHER UP TO BEAUFORT SCALE FORCE 4 AND/OR DOUGLAS SEA-STATE 3 (1.25MTR) WITH. NO ADVERSE CURRENTS. FAVOURABLE CURRENTS AND BAD WEATHER DAYS NOT TO BE TAKEN INTO CONSIDERATION FOR ANY PERFORMANCE CLAIM SUBMISSION. THE WORD “ABOUT” APPLIES TO BOTH SPEED AND CONSUMPTION. IT IS DEFINED AS A TOLERANCE OF 0.5 KNTS ON SPEED AND A TOLERANCE OF 5% ON BUNKER CONSUMPTION. MASTER HAS THE LIBERTY OF USING LSMGO WHILST MANOEUVRING IN/ OUT OF PORTS, RIVERS, CANALS, FAIRWAYS, CHANNELS, SHALLOW/NARROW/BUSY WATERS, STRAITS, RIVERS AND/OR WITHIN THE VICINITY OF RESTRICTED VISIBILITY. ADA

++

 

 

 

 

Kind regards,

TNS Shipbrokers - Antoniya

 

Skype: live:.cid.adba817154cf7291

WeChat: wxid_twwaqwr0eao712

Mob: +359 899 20 66 88

Bimco Members (reg. no. 116957)

----------------------------------------------------------------------------------------


Clarkson Hellas Ltd
T    :  +30 210 4586700
F    :  +30 210 4586799
E  :  handy@clarksons.gr




Niklas  / John

Gd day,

Seeing ultra at 17.5K from Taiwan and 18-19K from CJK

A/C GMT SINGAPORE
56/62,000DWT SDBC
MAX 20 YEARS OLD /  MIN 4X30 CRN
DELY CJK
ONE TCT WITH HLESS BUK(INTN. AMSUL IN BULK) TO WC MEXICO WITH DUR ABT 45-50 DAYS WOG
L/C : 15-20/SEP
RDLY :  1SP IN WC MEXICO(INT.MANZANILLO) ATDNSHINC
3.75% ADDCOM

Brgds





--- ORIGINAL MESSAGE ---
From: oslo@vegabulk.com
Sent: 31/08/2022 14:46:28
Subject: Vega Bulk Oslo, Tonnage UMAX NORTH CHINA 10/15 SEPT


VEGA BULK CARRIERS AS , OSLO

OPEN TONNAGE

HANTON TRADER 3, OPEN CJK 10/15 EX DOCK

MV HANTON TRADER 3 / BLT 2014 HANTONG /FLAG PHIL
SD BC SDWT 63434,89 ON 13,3 M /TPC 62,3 MT
CO2 FITTED / A60 / ITF / GRAIN 78771.04 M3 / IMO 9691436
5 H/H LOA 199,99 M / BEAM 32,26
GEAR 4 X 36 MT SWL + 4 PEINER GRABS
S/C LADEN/BALLAST  ABT 13,5 ON ABT 28,5 MT / ABT 14,5 ON ABT 29,5 MT
ECO LADEN/BALLAST ABT 12,5 ON ABT 23,5 MT / ABT 13,5 ON ABT 23,5 MT
IDLE 3,2 PER DAY/ WORKING ABT 6 MT PER DAY
ADA

TCT/LONG-SHORT PERIOD OK

BRGDS , NIKLAS


Vega Bulk Carriers A/S
 Address: Haakon VII Gate 1, 0161 Oslo, Norway
 General Manager Niklas Sindum +47 97482334
 Email: oslo@vegabulk.com
 SKYPE niklas.sindum
WWW.VEGABULK.COM
Disclaimer & Banking Notice : "This email with attachments, if any, are confidential and may be privileged and are intended only for the intended / authorised recipients of the sender. The information contained in this e-mail and any attachment(s) must not be published, copied, disclosed, or transmitted in any form to any person or entity unless expressly authorised by the sender. If you have received this email by mistake you are requested to delete it immediately and inform the sender by return e-mail. Vega Bulk Carriers AS, Norway will neither be liable nor responsible for any unauthorized transmission of this e-mail nor for any damage sustained as a result of this e-mail. "

EMAIL & BANKING FRAUD: We bank only with DNB Bank, Oslo, Norway and we don’t bank with any other banks or jurisdictions and our banking details are always mentioned in our Freight/Hire Invoices which we strongly request you to double check and verify with our EMAIL ID and WHATSAPP before setting up our beneficiary details and account in your Banking system. Due to the prevalence of email interception or email ID morphing frauds - do not act upon any messages amending bank account details without checking these with us by telephone on publicly available telephone numbers or via email directly with us – ACCOUNTS@VEGABULK.COM/ Business WhatsApp: +971-50-2065301 / https://www.vegabulk.com/contact-us/.

-------------------------------------------------------------------------------------------
COVID-19 DISRUPTION - Clarksons is fully equipped to work remotely in a technologically secure environment that ensures the group's continued operation and uninterrupted service to clients. Please however provide ALL documents via email as many of our offices in various locations are closed or inaccessible and thus we are NOT receiving or reading documents sent in a hard copy. We are also unable to send out hard copy documents including charterparties and invoices other than via email. Please check with your usual contacts to ensure receipt of important correspondence.
-------------------------------------------------------------------------------------------
All services undertaken are done so strictly in accordance with the terms and conditions applicable to those particular services, a copy of which is available at https://www.clarksons.com/terms-of-business/ Copies are also available on request.

This message is private and confidential. If you have received it in error, you are on notice of its status. Please notify us immediately by reply email and then delete this message from your system. Please do not copy it or use it for any purposes, or disclose its contents to any other person; to do so could be a breach of confidence. Emails may be monitored.

The Clarksons Platou Group are committed to protecting and respecting your privacy, for more information please see our privacy policy: https://www.clarksons.com/privacy-policy/

Details of Clarkson group companies and their regulators (where applicable) can be found at this url: http://www.clarksons.com/disclosure/.
-------------------------------------------------------------------------------------------
If you no longer wish to receive these emails please click the unsubscribe link: optout@clarksons.com . If you wish to update your preferences please reply to this email with your new contact details. The Clarksons Platou Group are committed to protecting and respecting your privacy, for more information please see our privacy policy: https://www.clarksons.com/privacy-policy/

If you would like to Opt-In to receive email invites for our global events please click the following Link: https://clkforms.wufoo.com/forms/rl28qny0eqviw5/.
-------------------------------------------------------------------------------------------

----------------------------------------------------------------------------

From: <chartering@vegastar.gr>
Date: Thu, Sep 1, 2022 at 12:17 PM
Subject: AGRICORE SMX/UMX UPTO PMX DELY TO MAKE NORTH VIETNAM
To: <oslo@vegabulk.com>


FM: VEGA STAR MARITIME SA
TEL:+30210-4287243/9855611, FAX:+30210-4287216
01/09/2022, 09:44:34, e-mail:chartering@vegastar.gr, Ref:328749-SK




GD DAY

PLS PROPOSE RATED TONNAGE FOR :

AGRICORE OR NOMIΒ  Β 
SMX/UMX UPTO PMX
DELYΒ TOΒ MAKEΒ NORTHΒ VIETNAM
LAYCAN SEP 5TH ONWARDS,2022
1Β TCTΒ TOΒ CHINA WITH BULK HARMLESS CGO
3.75% ADDΒ  PUS




Best Regards
Stefanos Kozakis
Mob: +30 690 68 99 006
Skype ID: stefanos.kozakis

[Message sent via SOFTWAY Communicator]
-------------------------------------------------------------------
good day

please offer for below fully firm cargo:

Bandırma /  Changshu
30.000 mtons Boron minerals in bb (+/- %20 depends on vsl's intake ),  maximum 12 tiers.
3000/3000 (All or some cargo could be directly transshipped into barges )
31 May / 07 June
1.25 pct comm

Grades:
15000 ton KIR Etibor-48 in 1200 kg BAFFLE BB with bottom,
15000 ton BIG Ground Colemanite in 1200 kg LAM BB with bottom,

sole cargo only
Prefer to BOX / or TWEEN / OPEN HATCH
max 20 years , geared 

no freight idea , best offers pls.

Best Regards
Devran Kutlu

ANG Shipping And Trading LLC
acting as broker only
--------------------------------------------------------------------------------------
C ANY MAY - JUNE 

LOADRATE 6.000 FHEX EIU

DISRATE 6.000 SHINC

3,75 %

++++++++++++++++++++++++++++
+
40.000MT UREA IN BULK ST 50'

B I KHOMEINI / MERSIN , TURKEY

L/C 1 / 10 JUNE

7.000 FHINC / 9.000 SHINC

3,75 %

+++++++++++++++++++++++++++++

40 / 50.000MT UREA IN BULK ST ABT 50'

LOADPORT : BANDAR ABBAS , IRAN DISPORT:  IMBITUBA OR SAO FRANCISCO DO SUL , BRAZIL

L/C ANY MAY / JUNE (CHRS FLEXIBLE ON QTTY AND DATES AS HV SEVERAL CARGOES)

LOADRATE : 6.000 FHEX EIU

DISRATE : 6.000 SHEX EIU (TRY SHINC)

3,75 %




-- 
Best   regards/Cristescu

As brokers only ,
-------------------------------------------------------------------------------
“ARION SHIPPING VSL” – OFF MARKET

 

PORTO ALEGRE 6/11 JUNE

 

ETB SFDS 24/5

ETCS SFDS 30/5

ETA PORTO ALEGRE 1/6

ETB PORTO ALEGRE 2/6

ETC/S PORTO ALEGRE 5/6

 

BUNKERS: REVERTING

LAST CARGOES: FERTS AND BEFORE SHE WAS AT THE DRYDOCK.

PREFER TRIPS TO MED/BLSEA.

 

M/V MASTRO MITROS

= = = = = = = = =

EX STAR CAPELLA - FLAG LIBERIA

45,601 MT DWT ON 11.576M SUMMER DRAFT

BUILT 09/2001  -  OSHIMA JAPAN

CLASS LR / FLAG LIBERIA

LOA/BM 179.99/31.00M

HOLDS CAPACITY: 57,256 CBM  OR 2,021,976 CFT

TPC 49.55 TONS

5 HO/HA (FOLDING TYPE)

-VENTILATION: HOLDS NATURAL

-NOT STRENGTHENED FOR ICE CLASS,

-HOLDS LADDERS: AUSTRALIAN TYPE

-HOLDS CO2 FITTED: YES

 

TONNAGE                  GROSS           NET       

INTERNATIONAL          25,388.00      15,284.00

 

CARGO HOLDS PARTICULARS

HOLD  GRAIN (M3)    BALE (M3)    HATCH DIMENSIONS     TANKTOP STRENGTH

                                 (L X B IN METERS)         (MT/M2)

#1   9,882.00       9,805.00     17.10 X 15.60            22.10

#2   12,634.00      12,454.00    21.60 X 15.60            16.00

#3   11,938.00      11,749.00    19.80 X 15.60            24.70

#4   12,617.00      12,437.00    21.60 X 15.60            16.00

#5   10,185.00      10,115.00    18.00 X 15.60            21.50

 

TOTAL  57,256.00      56,560.00

 

CARGO HOLDS TANK TOP DIMENSIONS (B X L IN METERS) HOLD NO 1: 6.92 X 22.35 X 27.26 HOLDS NO 2,3,4: 22.36 X 26.92 HOLD NO 5: 22.35 X 6.90 X 26.96

 

DECK CARGO GEAR

CRANES IHI 4 X 30MT ELEC-HYD CRANES

MAX OUTREACH FROM SHIP'S SIDE 9.5 METRES

SWL: 30T (HOOK MODE) / 24T (WHEN GRAB ATTACHED, INCLUDING WEIGHT OF THE GRAB) DESIGNED AND CLASS APPROVED TO OPERATE WITHIN THE DESIGNATED CAPACITIES ONLY WITH NO SIGNIFICANT MOVEMENT OF THE SHIP DUE TO WAVE ACTION AND CONDITIONS TO BE LESS THAN BEAUFORT FORCE 2, DOUGLAS SEASTATE 1. ONLY ONE CRANE TO BE USED IN A HOLD AT ANY ONE TIME. NOT ALL FOUR CRANES/GRABS TO WORK SIMULTANEOUSLY DURING LOADING / DISCHARGING OPERATIONS

 

CARGO GRABS:

- 4 X 6/10 M3 SMAG ELEC-HYD DEPENDING ON CARGO DENSITY (STOW FACTOR).

- BULK CARGO DENSITY LIMIT AT 6 M3 :  1.4 T/M3

  BULK CARGO DENSITY LIMIT AT 10 M3:  0.9 T/M3

 

VESSELS CRANES / GRABS TO BE OPERATED BY QUALIFIED SHORE PERSONNEL EMPLOYED AND PAID BY CHRTRS AT CHRTRS ENTIRE RISK / RESPONSIBILITY AND EXPENSE. IN CASE CHRTS WILL USE VSLS GRABS, TO GIVE MASTER FULL DESCRIPTION OF THE CARGO WITH ITS ACTUAL/CORRECT DENSITY SO AS TO ADJUST THE GRABS (IF NECESSARY), IN ORDER GRABS OPERATION BE COMPATIBLE WITH MANUFACTURERS MACHINERY DATA SPEC.

 

VESSEL'S GRABS HAVE ONLY BEEN USED WITH CLINKER CARGO LATELY. FOR ALL OTHER CARGOES  OWNERS ARE NOT IN POSITION TO GUARANTEE GRABS PROPER TIGHTNESS DURING USE. IN CASE CHARTERERS OPT TO USE VESSEL'S GRABS THEN SAME WILL BE USED AT CHARTERERS SOLE RISK / TIME AND OWNERS ARE NOT TO BE HELD RESPONSIBLE FOR CARGO SPILLAGE / GRAB MALFUNCTION (IF ANY).

 

BALLASTING OF HOLD

IN CASE BALLAST HOLD (NO.3) WILL HAVE TO BE BALLASTED DUE TO AIRDRAFT RESTRICTIONS AND/OR IMPOSED BY VESSEL'S STRENGTH CRITERIA DUE TO CHRTRS REQUIREMENTS OF LOAD/DISCH SEQUENCE, SAME TO BE DECLARED BY CHARTERERS ON VESSEL'S DELIVERY AND CHRTRS TO BE DEBITED THE L/SUM AMOUNT OF $2,500USD AGAINST OWNERS' EXPENSES FOR BALLASTING/DEBALLASTING CARGO HOLD. TIME REQUIRED TO BALLAST/DEBALLAST NO 3 CH, RINSE WITH FW AND PREPARE SAME TO ACCEPT CARGO TO COUNT, I.E.

VESSEL NOT TO BE OFF-HIRE. IN ANY CASE, BALLAST HOLD IS NOT TO BE BALLASTED IF THERE IS CARGO IN ADJACENT HOLDS (NO.2 AND NO.4).

 

 

SPEED N CONSUMPTION :

 

ABT 13.00K LADEN / ABT 13.25K BALLAST - ON ABT 26MTS VLSFO (380 CST) - NDAS

 

ALT ECO SPEED N CONSUMPTION : ABT 12/12.25K L/B ON ABT 21 MTS VLSFO - NDAS

 

IN PORT CONSUMPTION : IDLE ABT 2MTS VLSFO + ABT 0.5 MTS LSMGO

                      WW ABT 3.5MTS VLSFO + ABT 0.5 MTS LSMGO

 

PORT CONSUMPTION MAY BE INCREASED BY ABT 1 MT IFO WHEN TRADING AT COLD WEATHER CONDITIONS BELOW 5 DEG CELCIUS OR AT VERY HIGH

TEMPERATURE AREAS ABOVE 35 DEG CELCIUS.  

 

VSL'S SPEED N CONSUMPTION IS NOT GUARANTEED WHEN BURNING LSMGO ONLY.

 

ABOVE TO APPLY:

 

-FOR FULL DAYS AT SEA (I.E. NOON TO NOON) UNDER GOOD WEATHER  CONDITIONS WHICH TO BE DEFINED AS MAX BEAUFORT SCALE 4 AND DOUGLAS  SEA STATE 3 (MAX SIGNIFICANT WAVE HEIGHT 1,25M) AND NO  ADVERSE/FAVOURABLE CURRENTS OR NEGATIVE INFLUENCE OF SWELL FOR  THE ENTIRE PERIOD.

-BASIS NO DECK CARGO

-EXCLUDING SAILING IN CANALS, NARROW/ RESTRICTED WATERS AND CASES  WHERE MASTER ALTERS SPEED DUE TO REASONS OF SAFETY AND/OR POOR  VISIBILITY OR CHARTERERS ORDERS. THESE PERIODS ARE TO BE EXPRESSLY  EXCLUDED FROM PERFORMANCE CALCULATIONS

 

VESSEL'S PERFORMANCE TO BE ASSESSED ON AN AVERAGE BASIS TAKEN OVER THE ENTIRE CHARTER PERIOD, INCLUDING BOTH BALLAST AND LADEN VOYAGE(S).

 

'ABOUT' IS AGREED TO MEAN 0.5 KNOTS TOLERANCE ON VESSEL'S SPEED AND 5% UPWARD ALLOWANCE FOR CONSUMPTION

 

 

BUNKER SPECS : ISO F-8217:2010(E) RMG380 FOR VLSIFO (SULPHUR CONTENT NOT

               GREATER THAN 0.5%)

               ISO F-8217:2010(E) DMA FOR LSMGO (SULPHUR CONTENT NOT

               GREATER THAN 0.1%)

               FUEL OIL FROM TAR SANDS- AND SHALE- ORIGIN ARE NOT

               ALLOWED / ACCEPTED

 

IF VESSEL TRADE WITHIN 200 NAUTICAL MILES OF THE NORTH AMERICAN

COASTLINE (INCLUDING CANADA) AND/OR SECA AREAS WILL BE REQUIRED TO

USE FUEL OIL WITH MAXIMUM SULPHUR CONTENT OF 0.1%.IN CASE VESSEL

DOES NOT HAVE ON BOARD SUCH LOW SULPHUR FUEL OIL (LSFO),THEN TO

CONSUME MARINE GAS OIL (MGO) OF SULPHUR CONTENT LESS THAN 0.1%.

 

VESSEL CAN USE MGO IN MAIN ENGINE WHEN ENTERING/LEAVING PORT AND OR

MANOEUVRING IN NARROW/SHALLOW/CANAL/RIVER RESTRICTED WATERS AND/OR

CHANGING OF BALLAST OR ANY EMERGENCY SITUATION AS DEEMED NECESSARY BY

MASTER.

 

SEPARATE STEMS TO BE SEPARATED BY VESSEL’S TANKS AND NO MIXING OF

BUNKERS PERMITTED. BIMCO BUNKER FUEL SULPHUR CONTENT CLAUSE & BIMCO

BUNKER QUALITY CONTROL CLAUSE FOR TIME CHARTER PARTIES SHALL ALWAYS

APPLY. WHEN TRADING TO ECA AND/OR SECA AREAS, CHARTERERS TO

SUPPLY BUNKER IN ACCORDANCE WITH THE LATEST APPLICABLE REQUIREMENTS.

 

ALL DETS ABT

 

 

PLSD TO HEAR.

 

BRGRDS

----------------------------------------------------------------------------
grades :

grade 1 : abt  6000 mts

grade 2 : abt  11750 mts

grade 3 : abt  10000 mts

grade 4 : abt  2000 mts ,ferro chrome

***hold wise grade separation needed .

 

-- 
Best   regards/Cristescu

As brokers only ,
 
Phone: (+) 40-751-991111
Fax:   (+) 40-241-511739

EMAIL lidomar@lidomar.ro

Skype  cccatalin
   
In case the content of our messages are not of your interest please
kindly advise in order to remove you from the distribution list.
---------------------------------------------------------------------------------------


6/132930
Iskenderun / Uddevalla abt 29 750 mts chrome ore+ ferro chrome , 4 grades
05/20/2021
Team/ thodoris 

 

- MV FANOULA (IHI 55K - 4 X 35 AND 4 X 14 CBM)

- OPEN:  JORF LASFAR MAY 27-29

- ROB: 800 VLSFO /120 LSMGO

- LAST 5 CARGOES:  SULPHUR/SLAG/GRAIN/SALT/SALT

- TRY ANY

 

DEX BELOW:

 

M/V 'FANOULA' BUILT IHIMU YOKAHAMA 2008

56,557 MT DWT ON 12.735 SSW, TPC 56.5, BC **VESSEL IS EQUIPPED WITH A DUAL LOADLINE OF ABOUT 49,995 MT ON 11.578M (THERE IS A COST TO MOVE SAME FROM NKK)** LIBERIAN FLAG, LOA/BEAM 190.0M/32.26M, MOULDED DEPTH 18.1M

5 HO/HA - HATCH 1 - 14.56 X 18.60M, HATCHES 2-5 - 20.93 X 18.6M HYDRAULIC DOUBLE SKIN END FOLDING HATCH COVERS

GRAIN:  72,111 CUM, GT/NT 31,532/18,767

CR (IHI)  4 X 35 TONS/ 28 TONS IN GRABBING MODE, 26.0M OUTREACH (9.87M OVERSIDE) PLUS 4 X 14 CBM PEINER GRABS (ELECTRO HYDRAULIC) ADJUSTING DOWN TO 6.5 CBM MAX DENSITY 2.8 MT/CBM, MAX CARGO IN GRABS ABOUT 18.0 MT.

NO MORE THAN 1 CRANE TO BE WORKED AT A HATCH OR HOPPER OWNERS WILL NOT SUPPLY CRANEMEN FROM THE CREW CHARTERERS TO HAVE FREE USE OF VESSEL'S CRANES AND GRABS SP/CON ABOUT 13.5K L ON ABOUT 31T VLSIFO/ABOUT 14.0K B ON ABOUT 30T VLSFO 380 RMG NMGOAS ECO SPEED WOG ABOUT 13K ON ABOUT 23T VLSFO BALLAST/ABOUT 12.25K ON ABOUT 24.5T VLSFO LADEN PORT CONSUMPTION - IDLE 2.2T VLSFO + 0.1T LSMGO, WORKING 5.0T VLSFO + 0.1T LSMGO

CO2 FITTED/A60 BULKHEAD

ALL DETAILS 'ABOUTS'

 

Brgds

-----------------------------------------------------------------
SSOE
CARGO : POWDER MAP IN BULK  
QTY   : 30,000 MT +/- 10%  
LOAD PORT : 1/2 SP SB ZHANGJIAGANG OR YANGZHONG PORT 
LOAD RATE : 3,000 MT PWWD SHINC, 12 HOURS TT EIU. 
DISCHARGE PORT : 1/2 SP SB SA SAO FRANCISCO DU SUL, BRAZIL  
DISCHARGE RATE : 5,000 MT PWWD SASHEX EIU, NOR IN OFFICE HOURS
LAYCAN : 08TH - 10TH JUNE, 2021
ADD COM : 3.75% PU
Best regards,

 

Tony (Minh Tuan Vu)

Nueva Seas China

Shenzhen - China
---------------------------------------------------------------------------------
GRAIN, PETCOKE, SULPHUR  OK

LIBYA, LIBERIA, YEMEN, DJIBOUTI , SUDAN , KENYA, BANGLADESH OK

BOD : 550-600/50-100

Last 3 Cargoes :  Steel (last), Coal, Metcoke

 

SDBC LIB FLAG BLT 2012

DWT 57,045 MT ON 12.8 M SSW

CRANES 4 X 30 T / 22 MT BASIS GRAB OPERATION / GRAB 4X13

-BALLAST ABT 13.00 KNOTS ON ABT 30 MTS VLSFO + ABT 0.1 MTS LSMGO

-LADEN ABT 13.00 KNOTS ON ABT 31 MTS VLSFO + ABT 0.1 MTS LSMGO

-BALLAST ABT 12.00 KNOTS ON ABT 22 MT VLSFO + ABT 0.10 MT LSMGO

-LADEN ABT 11.50 KNOTS ON ABT 24 MT VLSFO + ABT 0.10 MT LSMGO

-IDLE ABT 3.50MT LSFO + ABT 0.1MT MGO

-GEAR WORKING ABT 3.50 MT - 5.50 MT LSFO DEPENDING ON NUMBER

OF CRANES WORKING + ABT 0.1 MT MGO.

 

Athens +30 211 102 6000 Dubai +971 4874 7136 London +44 20 3664 8040

Singapore +65 6496 5950 Tokyo +81 4589 9815

--------------------------------------------------------------------------------------------
POS A/O UPDATE/S

DIR/LOCAL HEAD OWNS WILL HAVE OPEN:=

 

SMX/SMAX/SUPRA

 

OUR-AFEA'S FIXTURE=

 

MV AGERI 56754 on 12.8mssw Blt '12 CND & GRBR............  USEC/Baltimore   27 MAY

                                                                                                               Psng KEY WEST 1/2  JUNE

                                                                                                                 ETA BRZL/SANTOS 14 JUNE

 

TC DESCR:=

 

MV AGERI

------------

-BUILT/DELIVERED 10/02/2012 BY COSCO GUANDONG SHIPYARD, CHINA

-DEADWEIGHT:

56,754 MT ON 12.800 M SUMMER DRAFT

58,327 MT ON 13.355 M TROPICAL FRESH WATER

56,754 MT ON 13.088 M FRESH WATER

58,327 MT ON 13.067 M TROPICAL

55,183 MT ON 12.533 M WINTER

-TPC AT SUMMER DRAFT 58.80 MT/cm

-LOA/LBP/BREADTH/DEPTH: 189.99/185.00/32.26/18.00

-GRT/NRT: 32,983/19,191

-PANAMA PC/UMS: 27,397

-SUEZ GRT/NRT: 33,934.90 / 30,983.06

-CLASS:NKK-NO:120225

-IMO: 9588574

-FLAG : LIBERIA

-HATCH DIMENSIONS (L x B): NO. 1: 18.86 x 18.26 M / No: 2, 3, 4, 5 : 21.32 x 18.26 M

-TANKTOP STRENGTH  NO. 1 / 2 / 3 / 4 / 5 RESP: 25.00 / 20.00 / 25.00 / 20.00 / 25.00 TONS/M2

-CARGO HOLDS CO2 FITTED

 -HOLD GRAIN CAPACITIES

HOLD     M3             CFT

N1      13,009.86   =  459,443.21

N2      15,333.25   =  541,993.72

N3      14,553.08   =  513,942.02

N4      15,333.27   =  541,494.43

N5      13,404.64   =  473,384.86

TOTAL: 71.634.09 = 2,529,758.24

-DRAFTS IN HEAVY/LIGHT BALLAST (50% BUNKERS)

FORE  8.48 / 5.39 MTRS                    

AFT   9.08 / 6.51 MTRS                    

MEAN  8.80 / 5.98 MTRS 

-LENGTH FROM FORWARD HATCH NO. 1 TO AFTER SIDE OF HATCH NO. 5: 140.22 MTRS   

-AIR DRAFT FROM WATER LINE TO TOP OF MAIN MAST IN HEAVY/BALLAST CONDITION(50% BUNKERS): 36.691 / 39.216 MTRS

HEAVY/LIGHT BALLAST (MEASUREMENT FROM MIDDLE OF EACH HATCH) (50% BUNKERS):

N 1  12.45 / 15.49 MTRS              

N 2  12.35 / 15.29 MTRS          

N 3  12.25 / 15.09 MTRS          

N 4  12.15 / 14.89 MTRS          

N 5  12.04 / 14.69 MTRS         

-DISTANCE FROM TANK TOP TO TOP OF H/COAMING: No2-5CH 20.12 MTRS , No1 20.32 MTRS

-SPEED/PROPULSION CONSUMPTIONS ARE GIVEN ON ABOUT BASIS (=5PCT) WITHOUT WARRANTY OR GUARANTEE UNDER GOOD WEATHER CONDITIONS NOT EXCEEDING BEAUFORT WIND SCALE 4 AND

DOUGLAS SEA STATE CODE 3 (DSS 3 MEANS SIGNIFICANT WAVE UP TO 1.25M) AND FREE OF ADVSERSE CURRENTS

ABT 14.2 KN BALLAST / 13.5 KN LADEN ON ABT 32.00 MT IFO 380 CST OR

ABT 13.5 KN BALLAST / 12.5 KN LADEN ON ABT 26.00 MT IFO 380 CST OR

ABT 12.5 KN BALLAST / 11.5 KN LADEN ON ABT 22.00 MT IFO 380 CST OR

ABT 11.5 KN BALLAST / 10.5 KN LADEN ON ABT 19.00 MT IFO 380 CST

VESSEL CONSUMES ABT 6.00 MT IFO 380 CST PER OPERATION WHEN EXCHANGING BALLAST AT SEA

VESSEL ALSO CONSUMES ABT 0.1 MT MGO PER DAY AT SEA FOR INCINERATOR PURPOSES

PORT CONSUMPTION IDLE: ABT 3.00 MT IFO 380 CST + 1.80 MT IFO 380 CST FOR BOILER

PORT CONSUMPTION WORKING: ABT 5.00 MT IFO 380 CST + 1.80 MT IFO 380 CST FOR BOILER

FOR BALLASTING/DEBALLASTING ADDITIONAL CONSUMPTION 3.00 MT IFO 380 CST

PER OPERATION

Consumption is based on IFO with calorific value 40.6MJ/kg at Reference conditions according to ISO 3046-1:2002

-IFO supplied and used on board must be in accordance with ISO 8217:2010

Vessel may burn mdo whilst navigating through rough water or with poor visibility, or manouvering/navigating in narrow waters/canals/straights/high traffic areas starting - stopping main engine and auxiliaries for ballast water exchange/holds cleaning or when using incinerator.

BUNKERS SPEC:

HFO RMG 380 ISO 8217 (2010) WITH MAX SULPHUR CONTENT 0.5%

 

FOR SECA/ECA TRADING MAXIMUM SULPHUR CONTENT 0.1%

Gasoil DMA max 0.1% Sulfur ISO 8210 (2010)

 

If ISO 2010 specification fuels are not available, Charterers may supply ISO 8217 2005 specification for RMG 380 and MGO DMA but always meeting the max allowable sulfur content allowed as per international regulations and MARPOL Annex VI.

 

ASSESSMENT FOR ANY UNDERPERFORMANCE SPEED CLAIM/OVER CONSUMPTION TO BE

CALCULATED ONLY FOR THE SPECIFIC PERIODS OF 'GOOD WEATHER' AS DEFINED UNDER

THIS CHARTER PARTY AND NOT TO BE EXTENDED/EXTRAPOLATED TO THE ENTIRETY OF THE

VOYAGE DURATION (SEA PASSAGE). CHARTERERS TO CONFIRM SUCH INSTRUCTIONS WILL CONVEYED TO

WEATHER ROUTING BUREAU UPON HIRING SUCH A SERVICE. THE EFFECTS OF CURRENTS DURING PERIODS OFGOOD WEATHER ARE TO BE EXPRESSLY EXCLUDED FROM THE PERFORMANCE ASSESSMENT

A day to be considered ‘’good weather day’’ only when there are at least 16 consecutive hours of ‘’good weather’’ as defined above

IN CASE VSL OVERPERFORMED IN EXCESS OF 5 PCT MARGIN OF ABOVE MENTIONED S+C FIGURES BENEFIT WILL BE FOR OWNERS

-MAIN ENGINE: MAN B&W 6S50MC-C  12,889 BHP = 9,480 KW AT 127 RPM, 2 STROKE, 6 CYLINDER

-GENERATORS: 3 X DOOSAN 5L23/30H, OUTPUT 884 BHP = 650 KW, 720 RPM, BURNING FUEL TYPE HFO 380CST - ALTERNATORS 3 x 600 KW, 440 V, 60 HZ

-DECK CRANES : I.H.I. 4 SETS x SWL 30 MT (SWL 24MT GRAB MODE) X RADIUS = 28 MTRS/OUTREACH = 11.87 MTRS

-GRABS: 4 X CAPACITY 12-6 M3 / SMAG ELECTROHYDRAULIC + 1 X RADIO REMOTE CONTROL CBM CAPACITY 12-6 M3

 - CHRTS HV THE OPTION TO USE VSL GRABS AT LOAD AND DISCHARGING FREE OF CHARGE BUT OWNERS NOT TO BE LIABLE FOR MALFUNCTIONING/ BREAKDOWN OF THOSE DURING THE ENTIRE LOADING/DISCHARGING OPERATIONS.

-LIGHTWEIGHT LDT ABT 10,926.89MT

-BALLAST:

LIGHT BALLAST: 16,741.69

HEAVY BALLAST: 31,658.60MT (INCLUSIVE C/H NO.3 FULL)

-BALLAST PUMPS 2 X 900 CBM/HOUR=1800 CBM/HOUR,

DEBALLASTING TIME INCL STRIPPING

IN LIGHT BALLAST CONDITION   DEBALLASTING  TIME ABOUT 12 HRS

AND IN HEAVY BALLAST CONDITION DEBALLASTING TIME ABOUT 20 HRS

ALL DTLS ABT

 

RGDS/AFEA
----------------------------------------------------------------------------------------------------
PLS PPSE

MV DENSA PUMA - SHUWAIKH 24/26 MAY
2013BLT
36.722 SDWT ON 10.92 M
GRT/NT 22709/12326
LOA/BM 186.40 M / 27.8 M
5H/5H, TPC 46.09 MT
GRAIN: 47.807,9 CBM
CRANES 4 X 30 TS + GRABS 4 X 12 CBM

Vessel desc Attached 
TC / voyage ok ; any direction

==
Best Regards

Mostafa Younis
Email: my@ssydubai.com
Mob: +971 521318060
Skype: mostafayounis88
--------------------------------------------------------------------------------------------------------
LD BULK

 

52/64.000 dwat grabber 12 cbm

Dely South Kalimantan

29 May/ 4 June 2021

1 tct abt 15-20 days with coal in bulk

Rdly Southeast Asia, intention Philippines

4.25 add pus

 

Cranes with minimum 28m boom required

 

Try period for the right candidate

 

Thanks / Best Regard
-------------------------------------------------------------------------------------------------
MV Yasa Venus, San Nicolas 28-30 May                                                             

290vlsfo/96 lsmgo

 

MV Clipper Kythira, Antonina 26-27 May                                                           

330mts vlsfo/140 lsmgo

 

 

M/V 'Clipper Kythira'

Marshall Islands, Built 2015

Singledeck/Bulk Carrier/Double Hull

abt. 63,272.6 mt Deadweight on 13.30 m SSW

L.O.A/Beam 199.9/32.26 meters

5 Holds/Hatches Folding

Hatchcovers

4 x 45 metric tonnes Cranes + 4 Grabs 22.5 cbm each

Grain 78,860.28 cbm

CO2/WWF Holdladder fitted

Ballast about 14.5kt on about 27.2 mt IFO/day

Laden about 14.0kt on about 30 mt IFO/day

Port idle/working about 3.0 mt / 4.5 mt IFO/day

While ballasting or deballasting operation, additional 1.5mt IFO per day.

Speed/Consumption given under good weather conditions upto Beaufort Scale 4 and Douglas Sea State

3, no adverse current. Vessel consumes DO in main engine when manoeuvering in narrow and confined

waters, in/out of port, channels, rivers and transiting canals.

Bunkers supplied to be in accordance with ISO Specifications:

IFO: 380 cst in accordance with ISO 8217:2005 (e) RMG

MDO: marine diesel oil in accordance with ISO 8217:2005 DMB

No mixing of bunkers allowed.

Vessel's gear is suitable for loading and/or discharging subject to the safe working limits of the Vessel's

cranes, grabs and equipment.

Tanktop

Strength :

Ho 1/3/5: 25 mt/m2

Ho 2/4: 19 mt/m2

Cubic

Breakdown:

Grain Bale

no 1: 13,976.64 13,948.69

no 2: 17,687.29 17,651.92

no 3: 15,365.50 15,334.76

no 4: 15,859.01 15,827.30

no 5: 15,971.84 15,939.89

Total: 78,860.28 78,702.56

HatchSizes

(meters):

no 1: 19,68 (l) x 18,26

no 2: 22,96 (l) x 18,26

no 3: 22,96 (l) x 18,26

no 4: 22,96 (l) x 18,26

no 5: 22,96 (l) x 18,26

Hold

Dimensions (meters on

flat tank top):

no 1: 27.06 (l) x 20.188

no 2: 33,62 (l) x 23,824

no 3: 26.24 (l) x 23,824

no 4: 28.70 (l) x 23,824

no 5: 31,98 (l) x 18.276

TPC

on SSW: 62.3

Class:

ABS

Int.

GR/NT: 36,294/21,607

Suez

GR/NT: 37,796.28/34,232.60

Panama

NT: 30,044

Deadweight

on winter marks: abt 61,546

Moulded

Dept: 18.5 meters

Call

Sign: V7JJ2

IMO

Reg Number: 9663116

 

Inmarsat

C: 453838947/453838948

Tel:

Fax:

+4589882184

email:

clipperkythira@gtships.com

Owners:

CFCL Umax Clip I LLC

Trust Company Complex, Ajeltake Road, Ajeltake Island,

Majuro MH 96960, Marshall Islands

Commercial

Manager: Clipper Bulk A/S

Owners

PANDI: North of England

all details about

Eco Speed:

Laden: about 12kts on abt 20mts VLSFO (380cst)

Ballast: about 12.5kts on abt 18mts VLSFO (380csts)

 

+++

 

M/V “YASA VENUS”

(IMO 9848118)

Deadweight: about 61.000 mt on 13.026 m Draft

LOA: 199.90 m

BEAM: 32.24 m

LBP: 197 m

Depth Moulded: 18.60 m

Type: Sıngle Deck / Bulk Carriers / Self Trimming

Built: End April / 2019 Dalian

Cosco Khi Ship Engineering Co., Ltd. (Dacks) China

Flag: Marshall Islands

International GRT / NRT about 35.000 / 20.200

TPC: about 60.4 (Summer Draft)

CO2 fitted in holds / certain App. B cargoes loadable in No. 5 hold /

2 x 25 t. steel coil in holds, strengtened holds 2 & 4 may be empty

Class: ABS

P. and I.: STANDARD

Holds / hatches: 5

Grain: about 77,528.3 cbm

Bale: 74,146.6 cbm

Cargo Holds (cbm) (including hatchcoaming)

Grain Bale

No 1 14,265.5 13,579.5

No 2 16,803.7 16,088.0

No 3 15,624.3 14,814.8

No 4 16,803.7 16,087.4

No 5 14,031.0 13,576.8

Total

(Cbm) 77,528.3 74,146.6

Hatch Dimensions (L X B)

No. 1 abt 18.69 x abt 18.60 m

No. 2/3/4/5 abt 21.36 x abt 18.60 m

Hold Dimensions (FWD / AFT bulk head x L)（dimensions for hold inner bottom）

No 1 : 10.24 / 24.00 x 29.370 m

No 2/3/4 : 24.00 / 24.00 x 32.04 m

No 5 : 24.00 / 12.60 x 26.70 m

Hatch covers tts , cylinder foldıng type, electrohydraulic

driven

M.A.N. B

AND W 6S50MEB9.3TII

2 stroke cycle type

4 x 30 mt electrohydraulıc

cranes Jiangsu Masada Heavy Industries Licencee of Mitsubishi

Grabs: 4 x 13 cbm (15 mtons payload) (adjustable capacity) Shanghai grab, radio controlled type grabs

Crane outreach: abt 11.8m (jib angle 25o)

All speed / consumption fıgures are to be consıdered as about (+/0.5

knot for speed and +/5%

for

consumption) are always subject to good weather which is defined as no adverse current a/o negative

influence of swell a/o moderate sea, wind not exceeding Beaufort Force 4 (four) a/o Douglas Sea State 3

(three) (sea wave height up to 1.25 meters and combined wave height up to 2.0 meters). Periods of

weather exceeding the above described good weather condıtıons are to be expressly excluded from the

evaluation of Vessels performance.

Charterers to supply first class quality bunkers strictly complyıng wıth ISO 82172010(

E), enabling maın

engine and generator engınes to operate wıthout any harmfull effects

Bunker Specificatios:

IFO grade 380 CST RMG 35 ISO 8217 2010(

e)

MDO grade DMA/DMB ISO 8217 2010(

e)

In case Charterers supply low sulphur MGO (DMA) for trading to ECA + EU zones the viscosity to be

minimum 2 CST at 40 degrees celcius.

Bunker testing to be organized by Owners / Managers but cost always to be for Charteres’ account.

Speed (knots) Consumption (T/day)

Laden

Speed (knots) Consumption (T/day) incl. auxiliaries at sea

11 16,5 MT IFO + 0,1 MT MDO (SUPER ECO/WOG)

12 20 MT IFO + 0,1 MT MDO (ECO/WOG)

12,5 22,5 MT IFO + 0,1 MT MDO (ECO/WOG)

13 25 MT IFO + 0,1 MT MDO

14 29 MT IFO + 0,1 MT MDO

Ballast

Speed (Knots) Consumption (T/Day) Incl. Auxiliaries At Sea

11 15 MT IFO + 0,1 MT MDO (SUPER ECO/WOG)

12 17 MT IFO + 0,1 MT MDO (ECO/WOG)

12,5 19 MT IFO + 0,1 MT MDO (ECO/WOG)

13 21 MT IFO + 0,1 MT MDO

14 25 MT IFO + 0,1 MT MDO

M/E may consume MDO during manoeuvers, durıng navigation in confined, restricted waters etc .

Generator Port Consumptıon (T/Day)

At Port Workıng / Idle: 5/2 mt IFO + 0,1 mt MDO

Boiler (only at port t/

day IFO) 1,5 ton/day

For every ballast / deballast / exchange of ballast operation (excluding BWTS) additional about 1 mt / day

IFO

As Vessel is a newbuilding Vessel, Speed / Consumption figures are given in good faith for guıdance only

wıthout guarantee. Same derived from data of existing sister ships however these data are subject to

change after evaluation of first three months performance to actual fıgures.

All details are about

 

+++

 



Thodoris Danikas
Handy/Supra | Athen
--------------------------------------------------------------------------------------------------------------------
gd day

 

close/direct, pls pps

 

 

 

open Singapore around 29-30 May 2021,  

 

vsl prefer clean cargo

 

 

MV.IKAN PARANG   

TYPE / BUILT SINGLE DECK BULK CARRIER / OCTOBER IN 2011 

CO2 / APPENDIX B FITTED 

YARD TAIZHOU KOUAN SHIPYARD, CHINA 

FLAG / CLASS / CALL SIGN / IMO SINGAPORE / ABS / 9V9099 / 9578787 DWT / DFT

(SUMMER) 56,697.1 MT ON 12.80 M SSW LOA / BEAM / TPC189.99 M / 32.26 M / 58.8 MT 

(SUMMER TPC) GRT / NRT33,010 / 19,270 MT HOLDS / HATCHES /HATCH TYPE5 HO / 5 

HA / FOLDING TYPE WEATHER TIGHT STEEL HATCH COVER HATCH SIZES ( L X B )1 : 

18.86 X 18.26 M 

2 : 21.32 X 18.26 M 

3 : 21.32 X 18.26 M 

4 : 21.32 X 18.26 M 

5 : 21.32 X 18.26 M 

CARGO GEARS4 X 30.0 MT ELECTRO HYDRAULIC CRANES 

GRABS12 CBM TOBU GRABS 

GRAIN / BALE 71,634.1 M3 / 68,200 M3 HOLD CAPACITY BREAKDOWN 

1 : 13,009.9 / 12,300 M3 

2 : 15,333.3 / 14,700 M3 

3 : 14,553.1 / 14,000 M3 

4 : 15,333.3 / 14,700 M3 

5 : 13,404.6 / 12,500 M3 

TANK TOP STRENGTH 1 : 25.00 MT/M2 

2 : 20.00 MT/M2 

3 : 25.00 MT/M2 

4 : 20.00 MT/M2 

5 : 25.00 MT/M2 

  

SPEED / CONSUMPTION: IN GOOD WEATHER CONDITIONS I.E: WINDS NOT EXCEEDING 

BEAUFORT SCALE FORCE 4, SEA / SWELL CONDITION NOT EXCEEDING DOUGLAS SEA STATE 

3, / 1.25M WITH NO ADVERSE CURRENTS OR NEGATIVE INFLUENCE OF SWELL. 

  

BUNKER SPECS ISO 8217:2010(E) 

DMA OR DMB FOR MDO 

BALLAST IFO ABT. 13.75 KNOTS ON ABT. 31.5.0 MT MDO ABT. 0.1 MT 

LADEN IFO ABT. 13.75 KNOTS ON ABT. 33.0 MT E MDO ABT. 0.1 MT 

PORT CONSUMPTION 

(IDLE) IFO ABT. 4.0 MT 

(WORKING) IFO ABT. 6.0 MT 

THE VESSEL IS ALLOWED TO CONSUME MDO WHEN ENTERING/LEAVING PORTS, DURING 

MANEUVERING AND SAILING IN CONFINED AND/OR SHALLOW WATERS, RIVERS, CANALS ETC 

AND WHEREVER NECESSARY AHL / ALTERNATE HOLDS LOADNO.2 & NO.4 MAY BE EMPTY 

TANK TOP STRENGTH 

1 : 25.00 MT/M2 

2 : 20.00 MT/M2 

3 : 25.00 MT/M2 

4 : 20.00 MT/M2 

5 : 25.00 MT/M2 

ALL DETAILS ARE ABOUT 

ECO SPEED AS REFERENCE ONLY AND WOG 

LADEN : ABT 12.5 KN AT 26.5 MT IFO+ 0.1MDO /DAY BALLAST : ABT 12.5 KN AT 25.5 

MT IFO+ 0.1MDO/DAY 

SEPARATE STEMS TO BE SEPARATED BY VESSEL’S TANKS AND NO MIXING OF BUNKERS PERMITTED.

BIMCO BUNKER FUEL SULPHUR CONTENT CLAUSE & BUNKER QUALITY CONTROL CLAUSE FOR TIME CHARTER PARTIES SHALL BE DEEMED TO BE INCORPORATED.

CHARTERERS TO SUPPLY BUNKER IN ACCORDANCE WITH THE LATEST APPLICABLE REQUIREMENTS, WHEN TRADING TO ECA AND/OR SECA AREAS,

 

AHL / CO2 FITTED

ALTERNATE HOLDS LOAD NO

 

ALL DETAILS ABOUT GIVEN IN GOOD FAITH  

 

 

B,rgds
AUSEA SHIPPING

 

SIWAN
-----------------------------------------------------------------------------------------------------

8,000/12,000 net mt bagged sugar

Kandla/Berbera

4/10 June

1500/1500 basis 4 sets of gear/4 hatches(or pro rata)

3.75%

 

 

Please refer: Sadiq Hussain/Barry Hicks/Will Weaving

 

 

16,100 net mt min/max bagged sugar

Suape + Recife/West Africa

4/10 June

1500/1000

6.25%

 

 

3,300 net mt min/max bagged sugar

Bejaia/1 port Tunisia

Prompt

1500mt load thurs 1700/sun 0800 ntc eiu

200mt per grd hatch satpmshex discharge

3.75%

 ------------------------------------------------------------

--/JOHN

 

CLOSE/LOCAL HEAD OWNERS REMAIN WITH THE FOLL UMAX

 

** EX OUR C/P, GRAIN CLEAN, CAN TRY ANY **

 

M/V CLEAR SKY - OPEN DAMIETTA 28-31 MAY'21

==

PANAMA FLAG BUILT 2014

ABT 63,600 DWT ON ABT 13.3 MTRS SSW , TPC 62.3

LOA 199.9 MTRS BEAM 32.26 MTRS

GRAIN CAP ABT 78771.05 CBM 5/5 HO/HA

CO2 FITTED IN CARGO HOLDS

A60 BULKHEAD FITTED

4 X HYDRAULIC OPERATED 36 TS MAX LIFTING CAPACITY

CRANES - 4 X 15 CBM GRABS (ADJUSTABLE)

SPEED/CONSUMPTION:

BALLAST: ABT 13.50 KNOTS ON ABT 23.1 MTS VLSFO INCL AUX ENGINES

LADEN  : ABT 13.50 KNOTS ON ABT 28.1 MTS VLSFO INCL AUX ENGINES

ECO SPEED (WOG) ASF

BALLAST: ABT 12.00 KNOTS ON ABT 18.2 MTS VLSFO INCL AUX ENGINES

LADEN  : ABT 12.00 KNOTS ON ABT 22.3 MTS VLSFO INCL AUX ENGINES

IDLE    BSS 24 HRS: ABT 2.5 MT VLSFO

WORKING BSS 24 HRS: ABT 5.5 MT VLSFO

BUNKER SPECS VLSFO 380 CST ISO 8217:2017

ALL DETAILS ABOUT GIVEN IN GOOD FAITH
------------------------------------------------------------------------------------------
SEAN CHENG

EMAIL:hmax@auseashipping.com

      AUSEABJ@163.COM

TEL：86-10-64039316

M/B: 86-18210807042

SKYPE:seancheng.30

WECHAT:18210807042

Panel of Baltic

 

This message is confidential and may contain legally privileged information. 
If you are not the intended recipient, you are hereby notified that you have received this message in error and that reading it,copying it, or in any way disclosing its content to any other person, is strictly unauthorized.
If you have received this message in error, please inform the sender by reply e-mail and then immediately delete this e-mail.
Unless otherwise stated or agreed, the information provided in this message is given in good faith and without guarantee.
-----------------------------------------------------------------------------------------------------------
WESTERN BULK SOUTH ATLANTIC TONNAGE

----------------------------------------------------------

 
REMAIN
  

M/V SPAR MIRA BAHIA BLANCA 26-27 MAY
BUILT 2010/YANGZHOU DAYANG/NIS FLAG/SDBC
58,018 MT DWAT ON 12,95 M SSW TPC 59,24
LOA/BEAM 189,99 M/32,26 M
5 HOLDS/HATCHES
GRAIN/BALE 71,549/69,760 CBM
CRANES 4X36 MT GRABS 4X15 CBM
GRT/NRT 32,839/19,559
CLASS: DNV
CO2 FITTED IN HOLDS
ABT 13,5 LADEN/14 BALLAST ON ABT 30,9 MT/29,4 MT IFO + ABT 0,1 MT MDO
PORT CONSUMPTION  WORKING ABT 4,5 MT IFO + ABT 0,1 MT MDO
IDLE  ABT 2,5 MT IFO + ABT 0,1 MT MDO
ECO SPEED ABT 12 LADEN/12,5 BALLAST ON ABT 22,5 MT IFO + ABT 0,1 MT MDO

 

 


Pareto Dry Cargo As
As brokers only

------------------------------------------------------------------------------------------
SHOWN 19K REDEL ATL FOR 4-6 MONTHS AND 21K REDEL WW 3-5 MONTHS

 

TO MOVE THIS WEEK OWNERS THINKING SOMETHING ARND MID LOW 20S RANGE FOR SP ATL REDEL OWISE WILL WAIT, LC CAN WORK 5-15 JUNE

 

-MV SEASTAR ENDEAVOUR 37DWT ON 10,92M, LAST DD Q1 2021 (DESC ATTACHED)

- LATEST SCHEDULE OPEN VITTORIA 8 JUNE, DISCH STEEL SLABS

-NIGERIA OK

-YEMEN OK

-ISRAEL OK

-FLEXI CARGO/TRADING

- CAN TRY SHORT UTPO LONG PERIOD WW, WILL ALSO LOOK AT FH

 

SPEED/CONSUMPTION

AT SEA: ABOUT 13.5 KNOTS (LADEN) ON ABOUT 25.5 TPD VLSFO/ LSMGO+ 2.2 TPD VLSFO/LSMGO AND

ABOUT 14.0 KNOTS (BALLAST) ON ABOUT 24.5 TPD VLSFO/ LSMGO+ 2.2 TPD VLSFO/LSMGO.

ABOVE FIGURES ARE BASIS GOOD WEATHER DAYS OF 24 HOURS FROM NOON TO NOON UP TO BEAUFORT

FORCE 3 OR DOUGLAS SEA STATE 3, MAX 1.25M COMBINED WAVES HEIGHT, NO ADVERSE CURRENTS

OR SWELL SAILING ON SUMMER DRAFTS.

IN PORT – WORKING: ABOUT 5.0 TPD VLSFO/ LSMGO

IN PORT – IDLE: ABOUT 3.5 TPD VLSFO/ LSMGO

 

FUEL OIL SPECIFICATION

VLSFO

LSMGO

ISO 8217:2017 CATEGORY ISO-F-RMG 380 SULPHUR CAP MAX 0.5%

ISO 8217:2017 CATEGORY ISO-F-DMA/DMB SULPHUS CAP MAX 0.1%

 

ECO SPEED/ CONSUMPTION

AT SEA: ABOUT 11.5 KNOTS (LADEN) ON ABOUT 18.2 TPD VLSFO/ LSMGO + 2.2 TPD VLSFO/LSMGO AND

ABOUT 12.0 KNOTS (BALLAST) ON ABOUT 16.4 TPD VLSFO/ LSMGO+ 2.2 TPD VLSFO/LSMGO.

ABOVE FIGURES ARE BASIS GOOD WEATHER DAYS OF 24 HOURS FROM NOON TO NOON UP TO BEAUFORT

FORCE 3 OR DOUGLAS SEA STATE 3, MAX 1.25M COMBINED WAVE HEIGHT, NO ADVERSE CURRENTS OR

SWELL SAILING ON SUMMER DRAFTS.

 --------------------------------------------------------------------
PLS PPSE 

- OPEN BAHODOPI, INDONESIA ARD 10TH JUNE
- BOD abt 300 - 400MT LSFO / abt 90-125 MT LSMD(G)O 
- Last 5 cargoes : metcoke (last) - wood pulp - steel - wheat - bagged rice 

M/V KEN EI 
PANAMA/2013 
SDBC CLASS NK ONOMICHI 
IMO NUMBER 9538983 
OHBOX-SHAPED IN HOLDS 2/3/4 
37,056 MT DWT ON 10.869 M SSW 
LOA/BM 177.85/28.6M 
GR/BL 45,790.76/45,294.41 CBM 
5 HOHA 4X30 TONS CRANE 
HATCH SIZE 
NO.1) 15.20 X 20.00 M 
NO.2-5) 22.40 X 24.00 M 
FOLDING TYPE HATCH COVER 
GRT/NRT 22,863/12,519 
HOLD CAPACITY BREAKDOWN 
HOLD GRAIN/BALE 
NO.1 6,500.34/6,424.34 
NO.2 10,080.65/9,954.32 
NO.3 10,104.69/10,002.6 
NO.4 10,061.64/9,959.91 
NO.5 9,043.44/8,953.24 CBM 
SPEED/CONSUMPTION 
(B) ABT 14.0KT/25.0MT VLSFO (FOR MAIN ENGINES)+ ABT 0.1 MT LSMGO (AUX) 
(L) ABT 13.5KT/24.5MT VLSFO (FOR MAIN ENGINES) + ABT 0.1 MT LSMGO (AUX) 
IN PORT WORKING ABT 3.8 MT VLSFO + 0.1 MT LSMGO 
IDLE ABT 2.2 MT VLSFO + 0.1 MT LSMGO 
ECO SPEED/CON - WOG ABT 12.5(B)/12.0(L)KN ON ABT 19.0 MT LSMGO IFO380 + ABT 0.1MT LSMGO 
- LSMGO: ISO 8217:2010 MGO (LESS THAN 0.1PCT SULPHUR) 
- VESSEL HAS LIBERTY TO BURN MDO WHILE MANEUVERING, SAILING OR NAVIGATING IN RESTRICTED/CONFINED WATERS, RIVERS, ESTUARIES, AND CANALS OR STAND-BY. 
- ABT MEANS 0.5 KTS FOR SPEED AND 5% FOR CONSUMPTION. 
- SPEED/CONSUMPTION ARE ONLY UNDER GOOD WEATHER CONDITIONS ALWAYS UP TO AND INCLUDING BEAUFORT SCALE 4 AND DOUGLAS SEA STATE 3 WITH NO ADVERSE CURRENT AND NO NEGATIVE INFLUENCE OF SWELL. 
ALL FIGURES ABOUT 
-----------------------------------------------------------------------------------
PLS PPSE 

- OPEN BAHODOPI, INDONESIA ARD 10TH JUNE
- BOD abt 300 - 400MT LSFO / abt 90-125 MT LSMD(G)O 
- Last 5 cargoes : metcoke (last) - wood pulp - steel - wheat - bagged rice 

M/V KEN EI 
PANAMA/2013 
SDBC CLASS NK ONOMICHI 
IMO NUMBER 9538983 
OHBOX-SHAPED IN HOLDS 2/3/4 
37,056 MT DWT ON 10.869 M SSW 
LOA/BM 177.85/28.6M 
GR/BL 45,790.76/45,294.41 CBM 
5 HOHA 4X30 TONS CRANE 
HATCH SIZE 
NO.1) 15.20 X 20.00 M 
NO.2-5) 22.40 X 24.00 M 
FOLDING TYPE HATCH COVER 
GRT/NRT 22,863/12,519 
HOLD CAPACITY BREAKDOWN 
HOLD GRAIN/BALE 
NO.1 6,500.34/6,424.34 
NO.2 10,080.65/9,954.32 
NO.3 10,104.69/10,002.6 
NO.4 10,061.64/9,959.91 
NO.5 9,043.44/8,953.24 CBM 
SPEED/CONSUMPTION 
(B) ABT 14.0KT/25.0MT VLSFO (FOR MAIN ENGINES)+ ABT 0.1 MT LSMGO (AUX) 
(L) ABT 13.5KT/24.5MT VLSFO (FOR MAIN ENGINES) + ABT 0.1 MT LSMGO (AUX) 
IN PORT WORKING ABT 3.8 MT VLSFO + 0.1 MT LSMGO 
IDLE ABT 2.2 MT VLSFO + 0.1 MT LSMGO 
ECO SPEED/CON - WOG ABT 12.5(B)/12.0(L)KN ON ABT 19.0 MT LSMGO IFO380 + ABT 0.1MT LSMGO 
- LSMGO: ISO 8217:2010 MGO (LESS THAN 0.1PCT SULPHUR) 
- VESSEL HAS LIBERTY TO BURN MDO WHILE MANEUVERING, SAILING OR NAVIGATING IN RESTRICTED/CONFINED WATERS, RIVERS, ESTUARIES, AND CANALS OR STAND-BY. 
- ABT MEANS 0.5 KTS FOR SPEED AND 5% FOR CONSUMPTION. 
- SPEED/CONSUMPTION ARE ONLY UNDER GOOD WEATHER CONDITIONS ALWAYS UP TO AND INCLUDING BEAUFORT SCALE 4 AND DOUGLAS SEA STATE 3 WITH NO ADVERSE CURRENT AND NO NEGATIVE INFLUENCE OF SWELL. 
ALL FIGURES ABOUT 
----------------------------------------------------------------------------------
Niklas / Dan

 

LATEST POSITIONS

 

ALLEGRA    35000    RIO GRANDE   1/3 JUNE

 

ARAYA        29800    SAFI                  1/3 JUNE

 

ALINDA       34000    BEIRA               4/5 JUNE

 

ARIETTA     34000     ITAQUI            6/11 JUNE

 

++

 

PLS PPS TCT/VOY/LEGS - FULL DESC/FURTHER DETAILS AVAILABLE

 

MV ALLEGRA

SDBC

BLT 2012

35,188 MTS DWAT ON 10.117M SSW

LOA 179.9 M / BEAM 30M

5 H/H

GRT/NRT 22,400/11,642

GRAIN 1,645,203 CFT

4 X 30 MT CRANES

ADA

 

MV ARAYA

SDBC - LOGS

BLT 2001

29,815 MTS DWAT ON 9.972M SSW – TPC 39.6 MTS

LOA 169.617M / BEAM 27.20M

5 H/H

GRT/NRT 17,697/10,808

GRAIN 1,324,455 CFT

4 X 30 MT CRANES

ADA

 

MV ALINDA

SDBC

BLT 2012

34,035 MTS DWAT ON 9.918M SSW – TPC 48.04 MTS

LOA 179.91M / BEAM 30M

5 H/H

GRT/NRT 22,223/11,534

GRAIN 1,636,433 CFT

4 X 35 MT CRANES

ADA

 

MV ARIETTA

SDBC

BLT 2012

34,111 MTS DWAT ON 9.91M SSW – TPC 48.2 MTS

LOA 179.91M / BEAM 30M

5 H/H

GRT/NRT 22,400/11,642

GRAIN 1,645,173 CFT

4 X 30 MT CRANES

ADA

 

Kind Regards,

Fairway Chartering (Dry Cargo) Ltd

------------------------------------------------------------------------------------
 

DATE: 5/20/2021  7:58 AM

REF: 200521-REF752299

- / ANDERS

DIRECT CHRTS HV :

LIGHTHOUSE NAVIGATION ATLANTIC ORDERS
30K DWT-SMAX  

DELY CANAKKALE

27 MAY-2 JUNE

1 TCT  STEELS

REDEL TAMPA-BARRANQUILLA

3.75 ADC + 1.25 PERACO

SMAX-UMAX  

DELY DJEN-DJEN

25–31 MAY

1 TCT CLINKER

REDEL WAFR LOME-TAKORADI

3.75 ADC + 1.25 PERACO
ALT SHORT PERIOD'''

doc=nlp(article_text)
for ent in doc.ents:
  print(ent.text,ent.label_)

# Load pre-existing spacy model
import spacy
nlp=spacy.load('en_core_web_sm')

# Getting the pipeline component
ner=nlp.get_pipe("ner")

# training data
TRAIN_DATA =[
    
("XIN HAI TONG",{"entities":[[3,15,"VESSEL"]]}),
("XIN HAI TONG ",{"entities":[[6,18,"VESSEL"]]}),
("LORENTZOS ",{"entities":[[6,15,"VESSEL"]]}),
("AKTI ",{"entities":[[5,9,"VESSEL"]]}),
("MEDI ADRIATICO ",{"entities":[[3,17,"VESSEL"]]}),
("MV MEDI ADRIATICO",{"entities":[[3,17,"VESSEL"]]}),
("MEDI ADRIATICO",{"entities":[[16,30,"VESSEL"]]}),
("MV GLORY SEA",{"entities":[[3,12,"VESSEL"]]}),
("MV.GLORY SEA",{"entities":[[0,12,"VESSEL"]]}),
("MV KLIMA",{"entities":[[3,8,"VESSEL"]]}),
("MV PROTECTOR ST. JOHN",{"entities":[[5,23,"VESSEL"]]}),
("MV PROTECTOR ST. JOHN",{"entities":[[3,21,"VESSEL"]]}),
("MV HANTON TRADER",{"entities":[[3,16,"VESSEL"]]}),
("M/V MASTRO MITROS",{"entities":[[4,17,"VESSEL"]]}),
("MV FANOULA",{"entities":[[5,12,"VESSEL"]]}),
("M/V FANOULA",{"entities":[[4,12,"VESSEL"]]}),
("MV AGERI",{"entities":[[3,8,"VESSEL"]]}),
("MV AGERI",{"entities":[[3,8,"VESSEL"]]}),
("MV DENSA PUMA",{"entities":[[3,13,"VESSEL"]]}),
("MV Yasa Venus",{"entities":[[3,13,"VESSEL"]]}),
("MV Clipper Kythira",{"entities":[[3,18,"VESSEL"]]}),
("M/V 'Clipper Kythira",{"entities":[[4,21,"VESSEL"]]}),
("M/V “YASA VENUS”",{"entities":[[4,16,"VESSEL"]]}),
("MV.IKAN PARANG",{"entities":[[0,14,"VESSEL"]]}),
("M/V CLEAR SKY",{"entities":[[4,13,"VESSEL"]]}),
("M/V SPAR MIRA BAHIA BLANCA",{"entities":[[4,26,"VESSEL"]]}),
("MV SEASTAR ENDEAVOUR",{"entities":[[4,21,"VESSEL"]]}),
("M/V KEN EI",{"entities":[[4,10,"VESSEL"]]}),
("M/V KEN EI",{"entities":[[4,10,"VESSEL"]]}),
("MV ALLEGRA",{"entities":[[3,10,"VESSEL"]]}),
("MV ARAYA",{"entities":[[3,8,"VESSEL"]]}),
("MV ALINDA",{"entities":[[3,9,"VESSEL"]]}),
("MV ARIETTA",{"entities":[[3,10,"VESSEL"]]}),
("MV MAINA",{"entities":[[3,8,"VESSEL"]]}),
("MV NILE CONFIDANTE",{"entities":[[3,18,"VESSEL"]]}),
("MV NATHAN BRANDON",{"entities":[[3,17,"VESSEL"]]}),
("MV AMS PEGASUS III",{"entities":[[5,20,"VESSEL"]]}),
("MV AMS PEGASUS III",{"entities":[[3,18,"VESSEL"]]}),
("MV BLISS OR SUB",{"entities":[[3,8,"VESSEL"],[12,15,"VESSEL"]]}),
("M/V CLIPPER TALENT",{"entities":[[4,18,"VESSEL"]]}),
("M/V SIRIUS",{"entities":[[4,10,"VESSEL"]]}),
("M/V CLIPPER AEGINA",{"entities":[[4,18,"VESSEL"]]}),
("M/V CLIPPER HOUSTON",{"entities":[[4,19,"VESSEL"]]}),
("M/V DUBAI SUN",{"entities":[[4,13,"VESSEL"]]}),
("M/V NORD SEAL",{"entities":[[4,13,"VESSEL"]]}),
("M/V CLIPPER HOUSTON",{"entities":[[4,19,"VESSEL"]]}),
("M/V 'DUBAI SUN'",{"entities":[[4,14,"VESSEL"]]}),
("M/V SEAHARMONY",{"entities":[[4,14,"VESSEL"]]}),
("M/V ITALIAN BULKER",{"entities":[[4,18,"VESSEL"]]}),
("M/V CRESSIDA",{"entities":[[4,12,"VESSEL"]]})
]

# Adding labels to the `ner`

for _, annotations in TRAIN_DATA:
  for ent in annotations.get("entities"):
    ner.add_label(ent[2])

# Disable pipeline components you dont need to change
pipe_exceptions = ["ner", "trf_wordpiecer", "trf_tok2vec"]
unaffected_pipes = [pipe for pipe in nlp.pipe_names if pipe not in pipe_exceptions]

# Import requirements
import random
from spacy.util import minibatch, compounding
from pathlib import Path
from spacy.training import Example
from spacy.scorer import Scorer
# TRAINING THE MODEL
with nlp.disable_pipes(*unaffected_pipes):

  # Training for 50 iterations
  for iteration in range(50):
    # shuufling examples  before every iteration
    random.shuffle(TRAIN_DATA)
    losses = {}

    for batch in spacy.util.minibatch(TRAIN_DATA, size=2):
      for text, annotations in batch:
        # create Example
        doc = nlp.make_doc(text)
        example = Example.from_dict(doc, annotations)
        # Update the model
        nlp.update([example], losses=losses, drop=0.3)
        print("Losses", losses)

import spacy
from spacy.scorer import Scorer
from spacy.tokens import Doc
from spacy.training.example import Example


def evaluate(ner_model, TRAIN_DATA):
    scorer = Scorer()
    example = []
    for input_, annot in TRAIN_DATA:
        pred = ner_model(input_)
        print(pred,annot)
        temp = Example.from_dict(pred, dict.fromkeys(annot))
        example.append(temp)
    scores = scorer.score(example)
    return scores

ner_model = spacy.load('en_core_web_sm') # for spaCy's pretrained use 'en_core_web_sm'
results = evaluate(ner_model, TRAIN_DATA)
print(results)

# Testing the model
doc = nlp("subhram")
print("Entities", [(ent.text, ent.label_) for ent in doc.ents])

doc = nlp("SEASTAR ENDEAVOUR ")
print("Entities", [(ent.text, ent.label_) for ent in doc.ents])

doc = nlp("......")
print("Entities", [(ent.text, ent.label_) for ent in doc.ents])

doc = nlp("MV NATHAN BRANDON")
print("Entities", [(ent.text, ent.label_) for ent in doc.ents])